services:
  app:
    build: .
    container_name: moderator
    ports:
      - "8080:8080"
    environment:
      - APP_SERVER_PORT=8080
      - APP_BASE_PATH=/api/v1
      - DEPLOY_ENV=production
      - JWT_SECRET=
      - DATABASE_URL=
