services:
  app:
    build: .
    container_name: moderator
    ports:
      - "8080:8080"
      - APP_SERVER_PORT=8080
      - APP_BASE_PATH=/api/v1
      - DEPLOY_ENV=production
      - JWT_SECRET=
      - POSTGRES_USER=vacmuser
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=moderator
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable
      - POSTGRES_HOST=postgres
      # Construct the URL using the literal values or .env references
      - DATABASE_URL=
